
services:
  messaging-gateway:
    image: ${DOCKER_REGISTRY:-ghcr.io/sentiric}/sentiric-messaging-gateway-service:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sentiric_messaging_gateway
    env_file:
      - ./.env
    ports:
      - "3003:3003" # Webhook'lar için
    networks:
      - sentiric-net
    restart: unless-stopped

networks:
  sentiric-net:
    name: ${NETWORK_NAME:-sentiric-net}
    driver: bridge