networks:
  sentiric-net:
    name: ${NETWORK_NAME:-sentiric-net}
    driver: bridge

services:
    
  messaging-gateway:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: sentiric-messaging-gateway-service
    env_file:
      - ./.env
    volumes:
      - ../sentiric-infrastructure/tls/certs:/etc/sentiric/tls:ro
    ports:
      - "${MESSAGING_GATEWAY_SERVICE_PORT}:${MESSAGING_GATEWAY_SERVICE_PORT}"
    networks:
      - sentiric-net
    profiles:
      - default
    restart: always