# docker-compose.dev.yml
# Service Geliştirme ortamı

networks:
  sentiric-net:
    name: "${NETWORK_NAME:-sentiric-net}"
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}
          gateway: ${NETWORK_GATEWAY}
  
volumes:
  # [presentation-gateway]: Arayüz ve Giriş Katmanı (Presentation Layer)
  # --------------------------------------------------     
  whatsapp_session:

services:
  # [presentation-gateway]: Arayüz ve Giriş Katmanı (Presentation Layer)
  # --------------------------------------------------
  messaging-gateway:
    image: ghcr.io/sentiric/sentiric-messaging-gateway-service:${TAG:-latest}
    env_file: ["${ENV_FILE_PATH}"]
    volumes: 
      - "${CONFIG_REPO_PATH}:/sentiric-config:ro"
      - "${CERTIFICATES_REPO_PATH}:/sentiric-certificates:ro"
      - "${ASSETS_REPO_PATH}:/sentiric-assets:ro"
      - whatsapp_session:/app/wweb_auth
    ports: 
      - "18020:${MESSAGING_GATEWAY_HTTP_PORT:-18020}"
      - "18022:${MESSAGING_GATEWAY_METRICS_PORT:-18022}"
      - "18023:${MESSAGING_GATEWAY_WS_PORT:-18023}"          
    networks:
      sentiric-net:
        ipv4_address: ${MESSAGING_GATEWAY_IPV4_ADDRESS}
    dns:
      - ${PRIMARY_DNS:-8.8.8.8}
      - ${SECONDARY_DNS:-1.1.1.1}        
    restart: always
    # depends_on: 
    #   rabbitmq: { condition: service_healthy }  